# Generated by Django 3.1.5 on 2021-01-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='SOME STRING', upload_to='', verbose_name='Изоброжение'),
        ),
    ]
