# Generated by Django 3.1.5 on 2021-01-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210119_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='opisanie',
            field=models.TextField(default='', max_length=300, verbose_name='Краткое описание'),
        ),
    ]
