# Generated by Django 3.1.5 on 2021-01-19 09:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_opisanie'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='', verbose_name='test'),
        ),
    ]
