# Generated by Django 3.1.5 on 2021-01-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210120_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=30, verbose_name='Цена'),
        ),
    ]
