# Generated by Django 3.1.5 on 2021-01-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210120_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgLoader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Название изоброжения')),
                ('image', models.ImageField(default='image', upload_to='', verbose_name='Изоброжение')),
            ],
        ),
    ]
